### ISSUE TITLE
Setting processing modes in ROS as a config parameter or a roslaunch parameter

### ISSUE THREAD

**Issue by SubMishMar** [nerian-vision/nerian_stereo#17]
Hi, 
Is there anyway to set the processing mode(Pass through/Rectify/Disparity) in ROS interface? Currently I do it in the web interface and then roslaunch the camera. But it will be highly convenient if it can be done through ROS.

Secondly, does the scenepro always start in disparity mode by default? Or it retains the mode it was set to earlier even after a reboot?

Thanks.

**Comment by nerian-vision** [comment]
Since version 3.4.0, the node now supports ROS parameters through dynamic_reconfigure. The operation mode is one of the exported parameters and can be changed at runtime.

Earlier versions of the node included a set of scripts to change the operation mode by calling the web interface. The scripts are still available on github:

https://github.com/nerian-vision/nerian_stereo/blob/3.3.2/scripts/config_device_passthru.sh
https://github.com/nerian-vision/nerian_stereo/blob/3.3.2/scripts/config_device_stereo.sh

The device will always start in the mode that was last set through the web interface.
